---
# Define the Lifecycle Environment level Host Groups
sat_lifecycle_environment_host_groups:
  - name: 'hg-ansible_automation_platform-rhel-8-dev'
    parent: 'hg-base/hg-rhel-8/hg-ansible_automation_platform-rhel-8'
    lifecycle_environment: 'lce-default-dev'
    content_view: 'ccv-ansible_automation_platform-rhel-8'
    locations:
      - 'loc-core'
    domain: 'home.b-lenz.eu'
    subnet: 'sn-172_31_41_0'
    activation_keys: 'ak-ansible_automation_platform-rhel-8-dev'
    openscap_proxy: '{{ inventory_hostname }}'
    content_source: '{{ inventory_hostname }}'
    organization: 'org-core'
    kickstart_repository: 'Red Hat Enterprise Linux 8 for x86_64 - BaseOS Kickstart 8.8'

  - name: 'hg-ansible_automation_platform-rhel-8-prod'
    parent: 'hg-base/hg-rhel-8/hg-ansible_automation_platform-rhel-8'
    lifecycle_environment: 'lce-default-prod'
    content_view: 'ccv-ansible_automation_platform-rhel-8'
    locations:
      - 'loc-core'
    domain: 'home.b-lenz.eu'
    subnet: 'sn-172_31_41_0'
    activation_keys: 'ak-ansible_automation_platform-rhel-8-prod'
    openscap_proxy: '{{ inventory_hostname }}'
    content_source: '{{ inventory_hostname }}'
    organization: 'org-core'
    kickstart_repository: 'Red Hat Enterprise Linux 8 for x86_64 - BaseOS Kickstart 8.8'

  - name: 'hg-ansible_automation_platform-rhel-9-dev'
    parent: 'hg-base/hg-rhel-9/hg-ansible_automation_platform-rhel-9'
    lifecycle_environment: 'lce-default-dev'
    content_view: 'ccv-ansible_automation_platform-rhel-9'
    locations:
      - 'loc-core'
    domain: 'home.b-lenz.eu'
    subnet: 'sn-172_31_41_0'
    activation_keys: 'ak-ansible_automation_platform-rhel-9-dev'
    openscap_proxy: '{{ inventory_hostname }}'
    content_source: '{{ inventory_hostname }}'
    organization: 'org-core'
    kickstart_repository: 'Red Hat Enterprise Linux 9 for x86_64 - BaseOS Kickstart 9.2'

  - name: 'hg-ansible_automation_platform-rhel-9-prod'
    parent: 'hg-base/hg-rhel-9/hg-ansible_automation_platform-rhel-9'
    lifecycle_environment: 'lce-default-prod'
    content_view: 'ccv-ansible_automation_platform-rhel-9'
    locations:
      - 'loc-core'
    domain: 'home.b-lenz.eu'
    subnet: 'sn-172_31_41_0'
    activation_keys: 'ak-ansible_automation_platform-rhel-9-prod'
    openscap_proxy: '{{ inventory_hostname }}'
    content_source: '{{ inventory_hostname }}'
    organization: 'org-core'
    kickstart_repository: 'Red Hat Enterprise Linux 9 for x86_64 - BaseOS Kickstart 9.2'

  - name: 'hg-default-rhel-8-dev'
    parent: 'hg-base/hg-rhel-8/hg-default-rhel-8'
    lifecycle_environment: 'lce-default-dev'
    content_view: 'ccv-default-rhel-8'
    locations:
      - 'loc-core'
    domain: 'home.b-lenz.eu'
    subnet: 'sn-172_31_41_0'
    activation_keys: 'ak-default-rhel-8-dev'
    openscap_proxy: '{{ inventory_hostname }}'
    content_source: '{{ inventory_hostname }}'
    organization: 'org-core'
    kickstart_repository: 'Red Hat Enterprise Linux 8 for x86_64 - BaseOS Kickstart 8.8'

  - name: 'hg-default-rhel-8-prod'
    parent: 'hg-base/hg-rhel-8/hg-default-rhel-8'
    lifecycle_environment: 'lce-default-prod'
    content_view: 'ccv-default-rhel-8'
    locations:
      - 'loc-core'
    domain: 'home.b-lenz.eu'
    subnet: 'sn-172_31_41_0'
    activation_keys: 'ak-default-rhel-8-prod'
    openscap_proxy: '{{ inventory_hostname }}'
    content_source: '{{ inventory_hostname }}'
    organization: 'org-core'
    kickstart_repository: 'Red Hat Enterprise Linux 8 for x86_64 - BaseOS Kickstart 8.8'

  - name: 'hg-default-rhel-9-dev'
    parent: 'hg-base/hg-rhel-9/hg-default-rhel-9'
    lifecycle_environment: 'lce-default-dev'
    content_view: 'ccv-default-rhel-9'
    locations:
      - 'loc-core'
    domain: 'home.b-lenz.eu'
    subnet: 'sn-172_31_41_0'
    activation_keys: 'ak-default-rhel-9-dev'
    openscap_proxy: '{{ inventory_hostname }}'
    content_source: '{{ inventory_hostname }}'
    organization: 'org-core'
    kickstart_repository: 'Red Hat Enterprise Linux 9 for x86_64 - BaseOS Kickstart 9.2'

  - name: 'hg-default-rhel-9-prod'
    parent: 'hg-base/hg-rhel-9/hg-default-rhel-9'
    lifecycle_environment: 'lce-default-prod'
    content_view: 'ccv-default-rhel-9'
    locations:
      - 'loc-core'
    domain: 'home.b-lenz.eu'
    subnet: 'sn-172_31_41_0'
    activation_keys: 'ak-default-rhel-9-prod'
    openscap_proxy: '{{ inventory_hostname }}'
    content_source: '{{ inventory_hostname }}'
    organization: 'org-core'
    kickstart_repository: 'Red Hat Enterprise Linux 9 for x86_64 - BaseOS Kickstart 9.2'
