---
# Define the Subnets
satellite_subnets:
  - name: 'sn-172_31_3_0'
    network: '172.31.3.0'
    mask: '255.255.255.0'
    gateway: '172.31.3.1'
    boot_mode: 'Static'
    ipam: 'None'
    tftp_proxy: '{{ inventory_hostname }}'
    template_proxy: '{{ inventory_hostname }}'
    discovery_proxy: '{{ inventory_hostname }}'
    remote_execution_proxies:
      - '{{ inventory_hostname }}'
    dns_primary: '172.31.3.1'
    dns_secondary: '172.31.3.47'
    domains:
      - 'office.int.scheib.me'
    organizations:
      - '{{ satellite_organization }}'
    locations:
      - '{{ satellite_location }}'
