---
# Define the Composite Content Views
sat_composite_content_views:
  - name: 'ccv-default-rhel-8'
    lifecycle_environments: "{{ satellite_lifecycle_environments | map(attribute='name') }}"
    components:
      - content_view: 'cv-rhcdn-base-rhel-8'
        latest: true

      - content_view: 'cv-rhcdn-satellite_6_client-rhel-8'
        latest: true

      - content_view: 'cv-elastic-elastic-el-8'
        latest: true

      - content_view: 'cv-zabbix-zabbix-rhel-8'
        latest: true

  - name: 'ccv-default-rhel-9'
    lifecycle_environments: "{{ satellite_lifecycle_environments | map(attribute='name') }}"
    components:
      - content_view: 'cv-rhcdn-base-rhel-9'
        latest: true

      - content_view: 'cv-rhcdn-satellite_6_client-rhel-9'
        latest: true

      - content_view: 'cv-zabbix-zabbix-rhel-9'
        latest: true

  - name: 'ccv-ansible_automation_platform-rhel-8'
    lifecycle_environments: "{{ satellite_lifecycle_environments | map(attribute='name') }}"
    components:
      - content_view: 'cv-rhcdn-base-rhel-8'
        latest: true

      - content_view: 'cv-rhcdn-ansible_automation_platform-rhel-8'
        latest: true

      - content_view: 'cv-rhcdn-satellite_6_client-rhel-8'
        latest: true

      - content_view: 'cv-elastic-elastic-el-8'
        latest: true

      - content_view: 'cv-zabbix-zabbix-rhel-8'
        latest: true

  - name: 'ccv-ansible_automation_platform-rhel-9'
    lifecycle_environments: "{{ satellite_lifecycle_environments | map(attribute='name') }}"
    components:
      - content_view: 'cv-rhcdn-base-rhel-9'
        latest: true

      - content_view: 'cv-rhcdn-ansible_automation_platform-rhel-9'
        latest: true

      - content_view: 'cv-rhcdn-satellite_6_client-rhel-9'
        latest: true

      - content_view: 'cv-zabbix-zabbix-rhel-9'
        latest: true
