---
# Merging all Global Parameters
sat_global_parameters: '{{ sat_global_parameters_ansible_provisioning +
                           sat_global_parameters_remote_execution +
                           sat_global_parameters_general }}'
